apiVersion: 1.0.0
metadata:
  name: felix-bootcamp-playground
projects:
  - name: Hogarama
    source:
      location: 'https://github.com/gepardec/hogarama.git'
      type: github
      branch: master
components:
  - alias: kube-tools
    image: 'fhochleitner/kube-tools:dev'
    mountSources: true
    command:
      - sleep
      - infinity
    memoryLimit: 512Mi
    type: dockerimage
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: redhat/java8/latest
    type: chePlugin
  - id: ms-kubernetes-tools/vscode-kubernetes-tools/latest
    type: chePlugin
commands:
  - name: Install Postgres
    actions:
      - component: kube-tools
        command: './install-pg.sh'
        workdir: '${CHE_PROJECTS_ROOT}/Hogarama/OpenShift3/Templates/postgres'
        type: exec
  - name: Tear-Down Postgres
    actions:
      - component: kube-tools
        command: 'helm uninstall postgresql'
        type: exec
